// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the article
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Publish Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date the article was published
   * - **API ID Path**: article.publishDate
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publishDate: prismic.DateField;

  /**
   * Featured Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.featuredImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredImage: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Navigation → Actions*
 */
export interface NavigationDocumentDataActionsItem {
  /**
   * Label field in *Navigation → Actions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.actions[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Actions*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.actions[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Homepage Label field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label for the homepage link
   * - **API ID Path**: navigation.homepageLabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  homepageLabel: prismic.KeyTextField;

  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;

  /**
   * Actions field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.actions[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  actions: prismic.GroupField<Simplify<NavigationDocumentDataActionsItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = HeroSliderSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
  /**
   * forcedTheme field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.forcedtheme
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/field#select
   */;
  forcedtheme: prismic.SelectField<"1" | "2">;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Variables → Next*
 */
export interface VariablesDocumentDataNextItem {
  /**
   * Translation field in *Variables → Next*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.next[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Item in *Variables → Previous*
 */
export interface VariablesDocumentDataPreviousItem {
  /**
   * Translation field in *Variables → Previous*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.previous[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Item in *Variables → Close*
 */
export interface VariablesDocumentDataCloseItem {
  /**
   * Translation field in *Variables → Close*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.close[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Item in *Variables → Open*
 */
export interface VariablesDocumentDataOpenItem {
  /**
   * Translation field in *Variables → Open*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.open[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Item in *Variables → Go to*
 */
export interface VariablesDocumentDataGoToItem {
  /**
   * Translation field in *Variables → Go to*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.go_to[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Item in *Variables → Send*
 */
export interface VariablesDocumentDataSendItem {
  /**
   * Translation field in *Variables → Send*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.send[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Item in *Variables → Book*
 */
export interface VariablesDocumentDataBookItem {
  /**
   * Translation field in *Variables → Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.book[].translation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  translation: prismic.KeyTextField;
}

/**
 * Content for Variables documents
 */
interface VariablesDocumentData {
  /**
   * Next field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.next[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  next: prismic.GroupField<Simplify<VariablesDocumentDataNextItem>>;

  /**
   * Previous field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.previous[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  previous: prismic.GroupField<Simplify<VariablesDocumentDataPreviousItem>>;

  /**
   * Close field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.close[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  close: prismic.GroupField<Simplify<VariablesDocumentDataCloseItem>>;

  /**
   * Open field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.open[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  open: prismic.GroupField<Simplify<VariablesDocumentDataOpenItem>>;

  /**
   * Go to field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.go_to[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  go_to: prismic.GroupField<Simplify<VariablesDocumentDataGoToItem>>;

  /**
   * Send field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.send[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  send: prismic.GroupField<Simplify<VariablesDocumentDataSendItem>>;

  /**
   * Book field in *Variables*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: variables.book[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  book: prismic.GroupField<Simplify<VariablesDocumentDataBookItem>>;
}

/**
 * Variables document from Prismic
 *
 * - **API ID**: `variables`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VariablesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VariablesDocumentData>,
    "variables",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | NavigationDocument
  | PageDocument
  | VariablesDocument;

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *CarouselSilder → Primary*
 */
export interface CarouselSilderSliceDefaultPrimary {
  /**
   * Title field in *CarouselSilder → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_silder.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *CarouselSilder → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_silder.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *CarouselSilder → Items*
 */
export interface CarouselSilderSliceDefaultItem {
  /**
   * Image field in *CarouselSilder → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel_silder.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CarouselSilder Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSilderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSilderSliceDefaultPrimary>,
  Simplify<CarouselSilderSliceDefaultItem>
>;

/**
 * Slice variation for *CarouselSilder*
 */
type CarouselSilderSliceVariation = CarouselSilderSliceDefault;

/**
 * CarouselSilder Shared Slice
 *
 * - **API ID**: `carousel_silder`
 * - **Description**: CarouselSilder
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSilderSlice = prismic.SharedSlice<
  "carousel_silder",
  CarouselSilderSliceVariation
>;

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *FeatureFocus → Primary*
 */
export interface FeatureFocusSliceDefaultPrimary {
  /**
   * Title field in *FeatureFocus → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_focus.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeatureFocus → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_focus.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for FeatureFocus Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureFocusSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureFocusSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureFocus*
 */
type FeatureFocusSliceVariation = FeatureFocusSliceDefault;

/**
 * FeatureFocus Shared Slice
 *
 * - **API ID**: `feature_focus`
 * - **Description**: FeatureFocus
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeatureFocusSlice = prismic.SharedSlice<
  "feature_focus",
  FeatureFocusSliceVariation
>;

/**
 * Default variation for HeroMarquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroMarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HeroMarquee*
 */
type HeroMarqueeSliceVariation = HeroMarqueeSliceDefault;

/**
 * HeroMarquee Shared Slice
 *
 * - **API ID**: `hero_marquee`
 * - **Description**: HeroMarquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroMarqueeSlice = prismic.SharedSlice<
  "hero_marquee",
  HeroMarqueeSliceVariation
>;

/**
 * Default variation for HeroParallax Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroParallaxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HeroParallax*
 */
type HeroParallaxSliceVariation = HeroParallaxSliceDefault;

/**
 * HeroParallax Shared Slice
 *
 * - **API ID**: `hero_parallax`
 * - **Description**: HeroParallax
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroParallaxSlice = prismic.SharedSlice<
  "hero_parallax",
  HeroParallaxSliceVariation
>;

/**
 * Default variation for HeroSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HeroSlider*
 */
type HeroSliderSliceVariation = HeroSliderSliceDefault;

/**
 * HeroSlider Shared Slice
 *
 * - **API ID**: `hero_slider`
 * - **Description**: HeroSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliderSlice = prismic.SharedSlice<
  "hero_slider",
  HeroSliderSliceVariation
>;

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSlice = prismic.SharedSlice<
  "pricing",
  PricingSliceVariation
>;

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NavigationDocumentDataActionsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      VariablesDocument,
      VariablesDocumentData,
      VariablesDocumentDataNextItem,
      VariablesDocumentDataPreviousItem,
      VariablesDocumentDataCloseItem,
      VariablesDocumentDataOpenItem,
      VariablesDocumentDataGoToItem,
      VariablesDocumentDataSendItem,
      VariablesDocumentDataBookItem,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CarouselSilderSlice,
      CarouselSilderSliceDefaultPrimary,
      CarouselSilderSliceDefaultItem,
      CarouselSilderSliceVariation,
      CarouselSilderSliceDefault,
      ContactFormSlice,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      FeatureFocusSlice,
      FeatureFocusSliceDefaultPrimary,
      FeatureFocusSliceVariation,
      FeatureFocusSliceDefault,
      HeroMarqueeSlice,
      HeroMarqueeSliceVariation,
      HeroMarqueeSliceDefault,
      HeroParallaxSlice,
      HeroParallaxSliceVariation,
      HeroParallaxSliceDefault,
      HeroSliderSlice,
      HeroSliderSliceVariation,
      HeroSliderSliceDefault,
      ImageSlice,
      ImageSliceVariation,
      ImageSliceDefault,
      PricingSlice,
      PricingSliceVariation,
      PricingSliceDefault,
      RichTextSlice,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
