// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
    call_to_action: dynamic(() => import('./CallToAction')),
    carousel_silder: dynamic(() => import('./CarouselSilder')),
    contact_form: dynamic(() => import('./ContactForm')),
    feature_focus: dynamic(() => import('./FeatureFocus')),
    hero_marquee: dynamic(() => import('./HeroMarquee')),
    hero_parallax: dynamic(() => import('./HeroParallax')),
    hero_slider: dynamic(() => import('./HeroSlider')),
    image: dynamic(() => import('./Image')),
    pricing: dynamic(() => import('./Pricing')),
    rich_text: dynamic(() => import('./RichText')),
};
